services:
  mysql:
    image: mysql:8.4
    container_name: wedmini-mysql
    command: --explicit_defaults_for_timestamp=ON
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: wedmini
      TZ: Asia/Bangkok
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p123456"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7
    container_name: wedmini-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20

  adminer:
    image: adminer
    container_name: minipos-adminer
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
